version: "3"
services:
  nginx:
    build: ./nginx
    container_name: nginx-container
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./www:/var/www/
    networks:
      todoNetwork:
        ipv4_address: 10.4.0.10


  php:
    build: ./php
    image: php:8.1-fpm
    expose:
      - 9000
    volumes:
      - ./www/:/var/www
    depends_on:
      - mysql
    networks:
      todoNetwork:
        ipv4_address: 10.4.0.11

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todolist
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      todoNetwork:
        ipv4_address: 10.4.0.12


networks:
  todoNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.4.0.10/16